-- Generated by Oracle SQL Developer Data Modeler 21.4.2.059.0838
--   at:        2022-10-17 22:21:18 BRT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE expenditure (
    expenditure_id   NUMBER(10) NOT NULL,
    expenditure      VARCHAR2(100) NOT NULL,
    description      VARCHAR2(255),
    value            NUMBER(10, 2) NOT NULL,
    date_expenditure DATE NOT NULL,
    date_creation    DATE NOT NULL,
    date_update      DATE,
    user_id          NUMBER(10) NOT NULL
);

ALTER TABLE expenditure ADD CONSTRAINT expenditure_pk PRIMARY KEY ( expenditure_id );

CREATE TABLE investiment (
    investiment_id   NUMBER(10) NOT NULL,
    investiment      VARCHAR2(100) NOT NULL,
    description      VARCHAR2(255),
    value            NUMBER(10, 2) NOT NULL,
    date_investiment DATE NOT NULL,
    date_creation    DATE NOT NULL,
    date_update      DATE,
    user_id          NUMBER(10) NOT NULL
);

ALTER TABLE investiment ADD CONSTRAINT investiment_pk PRIMARY KEY ( investiment_id );

CREATE TABLE profile (
    profile_id    NUMBER(10) NOT NULL,
    first_name    VARCHAR2(100) NOT NULL,
    middle_name   VARCHAR2(100),
    last_name     VARCHAR2(80) NOT NULL,
    born_date     DATE NOT NULL,
    gender        VARCHAR2(80),
    date_creation DATE NOT NULL,
    date_update   DATE,
    user_id       NUMBER(10) NOT NULL
);

ALTER TABLE profile ADD CONSTRAINT profile_pk PRIMARY KEY ( profile_id );

CREATE TABLE revenue (
    revenue_id    NUMBER(10) NOT NULL,
    revenue       VARCHAR2(100) NOT NULL,
    description   VARCHAR2(255),
    value         NUMBER(10, 2) NOT NULL,
    date_revenue  DATE NOT NULL,
    date_creation DATE NOT NULL,
    date_update   DATE,
    user_id       NUMBER(10) NOT NULL
);

ALTER TABLE revenue ADD CONSTRAINT revenue_pk PRIMARY KEY ( revenue_id );

CREATE TABLE "user" (
    user_id       NUMBER(10) NOT NULL,
    username      VARCHAR2(100) NOT NULL,
    email         VARCHAR2(255) NOT NULL,
    password      VARCHAR2(100) NOT NULL,
    date_creation DATE NOT NULL,
    date_update   DATE
);

ALTER TABLE "user" ADD CONSTRAINT user_pk PRIMARY KEY ( user_id );

ALTER TABLE "user" ADD CONSTRAINT user__un UNIQUE ( username );

ALTER TABLE expenditure
    ADD CONSTRAINT expenditure_user_fk FOREIGN KEY ( user_id )
        REFERENCES "user" ( user_id );

ALTER TABLE investiment
    ADD CONSTRAINT investiment_user_fk FOREIGN KEY ( user_id )
        REFERENCES "user" ( user_id );

ALTER TABLE profile
    ADD CONSTRAINT profile_user_fk FOREIGN KEY ( user_id )
        REFERENCES "user" ( user_id );

ALTER TABLE revenue
    ADD CONSTRAINT revenue_user_fk FOREIGN KEY ( user_id )
        REFERENCES "user" ( user_id );

CREATE SEQUENCE expenditure_expenditure_id_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;


CREATE SEQUENCE investiment_investiment_id_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE SEQUENCE profile_profile_id_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE SEQUENCE revenue_revenue_id_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE SEQUENCE user_user_id_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
